---

# -----------------
# Control variables (Travis Settings)
# -----------------
#
# PUBLISH_IMAGES        Should be 'yes' to enable publishing to Docker Hub.
#
# If you set PUBLISH_IMAGES you must also set the following: -
#
# DOCKER_USERNAME       If PUBLISH_IMAGES is 'yes'
# DOCKER_PASSWORD       If PUBLISH_IMAGES is 'yes'

os: linux
services:
- docker

stages:
- name: publish latest
  if: |
    branch = master \
    AND env(PUBLISH_IMAGES) = yes
- name: test latest
  if: |
    branch = master \
    AND env(PUBLISH_IMAGES) = yes
- name: publish tag
  if: |
    tag IS present \
    AND env(PUBLISH_IMAGES) = yes
- name: publish stable
  if: |
    tag IS present \
    AND tag =~ ^([0-9]+\.){1,2}[0-9]+$ \
    AND env(PUBLISH_IMAGES) = yes

before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

jobs:
  include:

  # Publish-stage jobs...
  # Every successful master build results in a latest image (above)
  # and every tag results in a tagged image in Docker Hub.
  # Tags that match a RegEx are considered 'official' tags
  # and also result in a 'stable' image tag.

  - stage: publish latest
    name: Latest Image
    script:
    # Build and push the pipelines-rdkit image and its sd-poster
    - docker build -t informaticsmatters/rdkit_pipelines:latest -f Dockerfile-rdkit .
    - docker push informaticsmatters/rdkit_pipelines:latest
    - docker build -t squonk/rdkit-pipelines-sdposter:latest -f Dockerfile-sdposter .
    - docker push squonk/rdkit-pipelines-sdposter:latest

  - stage: test latest
    name: Test Latest Image
    script:
    # Pull the latest pipelines-rdkit image
    # then clone the utils rep (containing the test engine)
    # and then run the tests
    - docker pull informaticsmatters/rdkit_pipelines:latest
    - git clone https://github.com/InformaticsMatters/pipelines-utils.git
    - cd pipelines-utils/src/groovy
    - groovy PipelineTester.groovy -indocker

  - stage: publish tag
    name: Tagged Image
    script:
    # Build and push the pipelines-rdkit image and its sd-poster
    - docker build -t informaticsmatters/rdkit_pipelines:${TRAVIS_TAG} -f Dockerfile-rdkit .
    - docker push informaticsmatters/rdkit_pipelines:${TRAVIS_TAG}
    - docker build -t squonk/rdkit-pipelines-sdposter:${TRAVIS_TAG} -f Dockerfile-sdposter .
    - docker push squonk/rdkit-pipelines-sdposter:${TRAVIS_TAG}

  - stage: publish stable
    name: Stable Image
    script:
    # Pull the corresponding pipelines-rdkit image tag and push it as 'stable'
    - docker pull informaticsmatters/rdkit_pipelines:${TRAVIS_TAG}
    - docker tag informaticsmatters/rdkit_pipelines:${TRAVIS_TAG} informaticsmatters/rdkit_pipelines:stable
    - docker push informaticsmatters/rdkit_pipelines:stable
    - docker pull squonk/rdkit-pipelines-sdposter:${TRAVIS_TAG}
    - docker tag squonk/rdkit-pipelines-sdposter:${TRAVIS_TAG} squonk/rdkit-pipelines-sdposter:stable
    - docker push squonk/rdkit-pipelines-sdposter:stable
