FROM informaticsmatters/rdkit_pipelines:latest
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"


USER root
RUN apt-get update -y && apt-get install zlib1g-dev make gcc git -y
RUN mkdir -p /usr/local/
WORKDIR /usr/local/
RUN git clone https://bitbucket.org/AstexUK/pli.git
WORKDIR /usr/local/pli
RUN make

RUN useradd -u 1001 -g 0 -m pli
USER 1001

WORKDIR /home/pli
ENV PLI_DIR /usr/local/pli
