FROM centos
MAINTAINER Tim Dudgeon <tdudgeon@informaticsmatters.com>

# An image to populate the Core with the contents of the
# Service Descriptors located in SD_SRC.

ENV SD_SRC /sd-src
WORKDIR ${SD_SRC}

# Copy all potential Service Descriptors into the image...
COPY src/python/ ${SD_SRC}/src/python/
COPY src/nextflow/ ${SD_SRC}/src/nextflow/
COPY post-service-descriptors.sh ${SD_SRC}/
RUN chmod 755 post-service-descriptors.sh

# On execution copy files from source to destination...
CMD ./post-service-descriptors.sh
