name: pipelines-utils
channels:
    - conda-forge
dependencies:
    - python=3.7.3
    - pip=20.0.2
    - rdkit=2019.09.2
    - pandas=1.0.1
    - scikit-learn=0.22.1
    - pip:
        - requests==2.24.0
        - matplotlib==2.2.*
        - molvs==0.1.1
        - standardiser==0.1.9
        - oddt==0.7
        - im-pipelines-utils
        - im-pipelines-utils-rdkit
