FROM informaticsmatters/rdkit:Release_2017_09_1
MAINTAINER Tim Dudgeon <tdudgeon@informaticsmatters.com>

USER root

# install pipelines python modules
RUN apt-get -y update && apt-get -y install python-matplotlib

COPY python /opt/python
RUN pip install -e /opt/python

