FROM busybox
MAINTAINER Tim Dudgeon <tdudgeon@informaticsmatters.com>

# An image to populate a Swervice Descriptor desitination directory
# (SD_DST) that is normally mounted when the image is runt
# with built-in Service Descriptor files in a source directory (SD_SRC).

ENV SD_SRC /sd-src
ENV SD_DST /sd-dst

RUN mkdir -p ${SD_SRC}

COPY python/ ${SD_SRC}/python/
COPY nextflow/ ${SD_SRC}/nextflow/

# Remove anything that doesn't look like a Service Descriptor...
RUN rm -f `find ${SD_SRC} -type f -not -name "*.json" -not -name "*.yml" -not -name "*.yaml"`

# On execution copy files from source to destination...
CMD ["cp", "-r", "/sd-src/", "/sd-dst"]
