---
name: build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.
# Here we build container images but don't push them
# and therefore do not require docker credentials.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - 'master'
  repository_dispatch:
    types:
    - pipelines-utils-rdkit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Build the images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build pipelines
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile-rdkit
        tags: informaticsmatters/rdkit_pipelines:latest
    - name: Build pipelines sdposter
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile-sdposter
        tags: squonk/rdkit-pipelines-sdposter:latest
    # Test the images
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run PipelineTester
      run: |
        git clone https://github.com/InformaticsMatters/pipelines-utils.git
        cd pipelines-utils
        ./gradlew runDockerPipelineTester
