---
name: build latest

# Actions on the main/master branch for every change.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches:
    - 'master'
  repository_dispatch:
    types:
    - pipelines-utils-rdkit
    - pipelines-utils

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Build the images
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build pipelines
      uses: docker/build-push-action@v2
      with:
        push: false
        file: Dockerfile-rdkit
        tags: informaticsmatters/rdkit_pipelines:latest
    # Test the images
    # We need Java and Groovy
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run pipeline tester
      uses: informaticsmatters/pipeline-tester-action@v1
    # Publish the images
    - name: Push
      run: docker push informaticsmatters/rdkit_pipelines:latest
    - name: Build and push pipelines sdposter
      uses: docker/build-push-action@v2
      with:
        push: true
        file: Dockerfile-sdposter
        tags: squonk/rdkit-pipelines-sdposter:latest
