---
name: build latest

# Actions on the main/master branch for every change.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Build the images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build pipelines
      uses: docker/build-push-action@v2
      with:
        push: false
        file: Dockerfile-rdkit
        tags: informaticsmatters/rdkit_pipelines:latest
    - name: Build pipelines sdposter
      uses: docker/build-push-action@v2
      with:
        push: false
        file: Dockerfile-sdposter
        tags: squonk/rdkit-pipelines-sdposter:latest
    # Test the images
    # We need Java and Groovy
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run PipelineTester
      run: |
        curl -s get.sdkman.io | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install groovy
        git clone https://github.com/InformaticsMatters/pipelines-utils.git
        cd pipelines-utils/src/groovy
        groovy PipelineTester.groovy -indocker
    # Publish the images
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push
      run: |
        docker push informaticsmatters/rdkit_pipelines:latest
        docker push squonk/rdkit-pipelines-sdposter:latest
